apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-quarkus-dev
spec:
  destination:
    namespace: quarkus-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./dev/quarkus-app
    repoURL: https://github.com/raffamendes/argocd-demo.git
    targetRevision: HEAD
