apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-quarkus-dev
spec:
  destination:
    namespace: quarkus-dev
    server: https://kubernetes.default.svc
  project: default
source:
  repoURL: 'https://github.com/raffamendes/argocd-demo.git'
  path: ./dev/quarkus-app
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: namespace
        value: quarkus-app
destination:
  server: 'https://kubernetes.default.svc'
  namespace: quarkus-app
syncPolicy:
  automated:
    prune: true
    selfHeal: true

