# Default values for quarkus-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

name: quarkus-app

namespace: app

image:
  name: nginx
  tag: IfNotPresent


service:
  type: ClusterIP
  port: 8080

